"""HTML report generation - clean, dependency-free, single self-contained file."""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

_STYLE = """
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
       background: #0f1115; color: #e6e6e6; margin: 0; padding: 2rem; }
h1 { color: #58a6ff; }
table { border-collapse: collapse; width: 100%; margin-top: 1rem; }
th, td { border: 1px solid #30363d; padding: 8px 12px; text-align: left; }
th { background: #161b22; color: #58a6ff; }
tr:nth-child(even) { background: #161b22; }
.status-up, .status-open, .status-pass { color: #3fb950; font-weight: 600; }
.status-down, .status-closed, .status-fail { color: #f85149; font-weight: 600; }
.status-warn, .status-filtered { color: #d29922; font-weight: 600; }
.summary { margin-top: 1rem; padding: 1rem; background: #161b22; border-radius: 8px; }
footer { margin-top: 2rem; color: #6e7681; font-size: 0.85rem; }
"""


def _status_class(value: str) -> str:
    return f"status-{str(value).lower()}"


def scan_to_html(scan_data: dict[str, Any]) -> str:
    """Render a scan-summary dict to a self-contained HTML report."""
    hosts = scan_data.get("hosts", [])
    rows = []
    for host in hosts:
        status = host.get("status", "")
        rows.append(
            "<tr>"
            f"<td>{html.escape(str(host.get('ip', '')))}</td>"
            f"<td class='{_status_class(status)}'>{html.escape(status.upper())}</td>"
            f"<td>{html.escape(str(host.get('latency_ms')) + ' ms' if host.get('latency_ms') is not None else '-')}</td>"
            f"<td>{html.escape(host.get('hostname') or '-')}</td>"
            f"<td>{html.escape(host.get('mac') or '-')}</td>"
            f"<td>{html.escape(host.get('vendor') or '-')}</td>"
            "</tr>"
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>NetAudit Scan Report</title>
<style>{_STYLE}</style>
</head>
<body>
<h1>NetAudit Network Scan Report</h1>
<table>
<tr><th>IP</th><th>Status</th><th>Latency</th><th>Hostname</th><th>MAC</th><th>Vendor</th></tr>
{"".join(rows)}
</table>
<div class="summary">
<strong>Discovered:</strong> {scan_data.get("discovered", len(hosts))} &nbsp;|&nbsp;
<strong>Online:</strong> {scan_data.get("online", "-")} &nbsp;|&nbsp;
<strong>Offline:</strong> {scan_data.get("offline", "-")} &nbsp;|&nbsp;
<strong>Duration:</strong> {scan_data.get("duration_s", "-")}s
</div>
<footer>Generated by NetAudit</footer>
</body>
</html>
"""


def generic_to_html(title: str, data: Any) -> str:
    """Fallback renderer: pretty-print arbitrary JSON-like data inside <pre>."""
    body = html.escape(json.dumps(data, indent=2, default=str))
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{html.escape(title)}</title>
<style>{_STYLE}</style>
</head>
<body>
<h1>{html.escape(title)}</h1>
<pre>{body}</pre>
<footer>Generated by NetAudit</footer>
</body>
</html>
"""


def write_html_report(content: str, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path
